const mockFound = {
  user: {
    email: 'test8@email.com',
    userNumber: 164,
  },
  employee: {
    employeeNumber: 2008,
    lastName: 'Murphy',
    firstName: 'Diane',
    extension: 'x5800',
    officeCode: '1',
    reportsTo: null,
    jobTitle: 'Staff',
    userNumber: 164,
    isActive: 1,
  },
};

const mockGetAll = [
  {
    employeeNumber: 1002,
    lastName: 'Murphy',
    firstName: 'Diane',
    extension: 'x5800',
    officeCode: '1',
    reportsTo: null,
    jobTitle: 'President',
    userNumber: 1,
    roleNumber: 1,
    email: 'dmurphy@classicmodelcars.com',
    isVerified: 0,
  },
  {
    employeeNumber: 1056,
    lastName: 'Patterson',
    firstName: 'Mary',
    extension: 'x4611',
    officeCode: '1',
    reportsTo: 1002,
    jobTitle: 'VP Sales',
    userNumber: 5,
    roleNumber: 3,
    email: 'mpatterso@classicmodelcars.com',
    isVerified: 0,
  },
  {
    employeeNumber: 1088,
    lastName: 'Patterson',
    firstName: 'William',
    extension: 'x4871',
    officeCode: '6',
    reportsTo: 1002,
    jobTitle: 'Sales Manager (APAC)',
    userNumber: 2,
    roleNumber: 2,
    email: 'wpatterson@classicmodelcars.com',
    isVerified: 0,
  },
  {
    employeeNumber: 1102,
    lastName: 'Bondur',
    firstName: 'Gerard',
    extension: 'x5408',
    officeCode: '4',
    reportsTo: 1002,
    jobTitle: 'Sale Manager (EMEA)',
    userNumber: 3,
    roleNumber: 2,
    email: 'gbondur@classicmodelcars.com',
    isVerified: 0,
  },
  {
    employeeNumber: 1143,
    lastName: 'Bow',
    firstName: 'Anthony',
    extension: 'x5428',
    officeCode: '1',
    reportsTo: 1002,
    jobTitle: 'Sales Manager (NA)',
    userNumber: 4,
    roleNumber: 2,
    email: 'abow@classicmodelcars.com',
    isVerified: 0,
  },
];

const mockCreated = {
  employee: {
    employeeNumber: 2000,
    lastName: 'Murphy',
    firstName: 'Diane',
    extension: 'x5800',
    officeCode: '1',
    reportsTo: null,
    jobTitle: 'Staff',
    userNumber: 31,
  },
  user: {
    email: 'mock@email.com',
    password: '$2b$10$G2hLuOKwjNuK4kmzWySDVedKnxaRxcxLLIdyiUl552t2Zq20rSh.W',
    userNumber: 31,
  },
};

const updatedEmployee = {
  employeeNumber: 2000,
  lastName: 'Murphy',
  firstName: 'Diane',
  extension: 'x5800',
  officeCode: '1',
  reportsTo: null,
  jobTitle: 'Staff',
  roleNumber: 3,
  userNumber: 32,
};

const deletedEmployee = {
  deletedEmployee: 1,
  deletedUser: 1,
};

const mockGraphFetched = [
  {
    employeeNumber: 1611,
    lastName: 'Fixter',
    firstName: 'Andy',
    extension: 'x101',
    officeCode: '6',
    reportsTo: 1088,
    jobTitle: 'Sales Rep',
    userNumber: 17,
    roleNumber: 3,
    isActive: 1,
    email: 'afixter@classicmodelcars.com',
    customers: [
      {
        customerNumber: 114,
        customerName: 'Australian Collectors, Co.',
        contactLastName: 'Ferguson',
        contactFirstName: 'Peter',
        phone: '03 9520 4555',
        addressLine1: '636 St Kilda Road',
        addressLine2: 'Level 3',
        city: 'Melbourne',
        state: 'Victoria',
        postalCode: '3004',
        country: 'Australia',
        salesRepEmployeeNumber: 1611,
        creditLimit: '117300.00',
        userNumber: 39,
        roleNumber: 4,
        isActive: 1,
      },
      {
        customerNumber: 276,
        customerName: "Anna's Decorations, Ltd",
        contactLastName: "O'Hara",
        contactFirstName: 'Anna',
        phone: '02 9936 8555',
        addressLine1: '201 Miller Street',
        addressLine2: 'Level 15',
        city: 'North Sydney',
        state: 'NSW',
        postalCode: '2060',
        country: 'Australia',
        salesRepEmployeeNumber: 1611,
        creditLimit: '107800.00',
        userNumber: 92,
        roleNumber: 4,
        isActive: 1,
      },
      {
        customerNumber: 282,
        customerName: 'Souveniers And Things Co.',
        contactLastName: 'Huxley',
        contactFirstName: 'Adrian',
        phone: '+61 2 9495 8555',
        addressLine1: 'Monitor Money Building',
        addressLine2: '815 Pacific Hwy',
        city: 'Chatswood',
        state: 'NSW',
        postalCode: '2067',
        country: 'Australia',
        salesRepEmployeeNumber: 1611,
        creditLimit: '93300.00',
        userNumber: 94,
        roleNumber: 4,
        isActive: 1,
      },
      {
        customerNumber: 333,
        customerName: 'Australian Gift Network, Co',
        contactLastName: 'Calaghan',
        contactFirstName: 'Ben',
        phone: '61-7-3844-6555',
        addressLine1: '31 Duncan St. West End',
        addressLine2: null,
        city: 'South Brisbane',
        state: 'Queensland',
        postalCode: '4101',
        country: 'Australia',
        salesRepEmployeeNumber: 1611,
        creditLimit: '51600.00',
        userNumber: 109,
        roleNumber: 4,
        isActive: 1,
      },
      {
        customerNumber: 471,
        customerName: 'Australian Collectables, Ltd',
        contactLastName: 'Clenahan',
        contactFirstName: 'Sean',
        phone: '61-9-3844-6555',
        addressLine1: '7 Allen Street',
        addressLine2: null,
        city: 'Glen Waverly',
        state: 'Victoria',
        postalCode: '3150',
        country: 'Australia',
        salesRepEmployeeNumber: 1611,
        creditLimit: '60300.00',
        userNumber: 147,
        roleNumber: 4,
        isActive: 1,
      },
    ],
  },
];

export {
  mockFound,
  mockGetAll,
  mockCreated,
  updatedEmployee,
  deletedEmployee,
  mockGraphFetched,
};
